### PR TITLE
Add the ability to exclude columns

### PR DESCRIPTION
**Pull request by imcfarla2003**
Add a new config variable EXCLUDED_TESTS which is a comma delimited list of tests to ignore.

This is useful for combo tests where you don't want to see the underlying tests

### CODE REVIEW

**Comment by daduke** [comment]
this is already in xymon2json: `default['test'] = '[^libs]'` and can even be specified in the URL: `xymondash/?test=[^dirtyvcs,^libs]` - do we really need another config variable?

**Comment by imcfarla2003** [comment]
There is no way to pass it through from the index page and this list will
be different for each implementation.

Regards,

Iain

On 6 May 2019 06:23, Christian Herzog <notifications@github.com> wrote:

> this is already in xymon2json: default['test'] = '[^libs]' and can even
> be specified in the URL: xymondash/?test=[^dirtyvcs,^libs] - do we
> really need another config variable?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the
thread[2].
> [ { "@context": "http://schema.org", "@type": "EmailMessage",
> "potentialAction": { "@type": "ViewAction", "target":
> "https://github.com/daduke/Xymondash/pull/9#issuecomment-489503793",
> "url":
> "https://github.com/daduke/Xymondash/pull/9#issuecomment-489503793",
> "name": "View Pull Request" }, "description": "View this Pull Request on
> GitHub", "publisher": { "@type": "Organization", "name": "GitHub",
> "url": "https://github.com" } } ]



Links:
------
[1] https://github.com/daduke/Xymondash/pull/9#issuecomment-489503793
[2]

**Comment by daduke** [comment]
> There is no way to pass it through from the index page 

I do not understand what this means. I just showed you how to pass it via URL..

> and this list will be different for each implementation

ok let's make `default['test']` a config setting then instead of introducing another one

**Comment by imcfarla2003** [comment]
I just tried what you suggested and yes that works but...

I have 24 tests one for each possible drive above c: "frag_c", "frag_d" which as a combo column become "frag".  My combo.cfg contains lines such as:
server.internal.domain.frag=(server.internal.domain.frag\_c && server.internal.domain.frag\_e)

I never want to be able to see any of the individual columns but I also want to retain the ability to filter by a specific test so my config.ini has:
EXCLUDE_TESTS="frag_c,frag_d,frag_e,frag_f,frag_g,frag_h,frag_i,frag_j,frag_k,frag_l,frag_m,frag_n,frag_o,frag_p,frag_q,frag_r,frag_s,frag_t,frag_u,frag_v,frag_w,frag_x,frag_y,frag_z"

Howerver, sometimes I want to hide the "msgs" column depending on external requirements so keeping the functionality for excluding tests on the URL is still required.

Does that make sense and explain why I think we need a new config.ini variable.

**Comment by daduke** [comment]
> I have 24 tests one for each possible drive above c: "frag_c", "frag_d" which as a combo column become "frag". My combo.cfg contains lines such as:
> server.internal.domain.frag=(server.internal.domain.frag_c && server.internal.domain.frag_e)
> 
> I never want to be able to see any of the individual columns but I also want to retain the ability to filter by a specific test so my config.ini has:
> EXCLUDE_TESTS="frag_c,frag_d,frag_e,frag_f,frag_g,frag_h,frag_i,frag_j,frag_k,frag_l,frag_m,frag_n,frag_o,frag_p,frag_q,frag_r,frag_s,frag_t,frag_u,frag_v,frag_w,frag_x,frag_y,frag_z"

how about `test=[^frag_] then? To be honest, this use case is a bit too spacy for my taste and I might have to ask you to patch this line in your local copy.
I think the interplay between the URL parameter and the exclude list would create more confusion than benefit for most people.

**Comment by imcfarla2003** [comment]
How about if we collect the required columns from the xymonserver.cfg instead of adding a new variable?

in config.sh:
#cbtain the test to exclude from the xymongen options
XYMONDIR=${CRITICAL:0:${#CRITICAL}-13}
XYMONGENOPTS=`cat $XYMONDIR/xymonserver.cfg | grep -v ^# | grep XYMONGENOPTS=`
EXCLUDE_TESTS=`echo $XYMONGENOPTS | awk '{split($0,a,"--")} END {for (key in a) {print a[key]}}' | grep ^ignorecolumns | awk '{split($0,a,"="); b=gensub(/^[ \t]*|[ \t]*$/,"","g",a[2]); print b}'`

**Comment by daduke** [comment]
this is not valid shell code

**Comment by daduke** [comment]
are you still interested in this?

**Comment by imcfarla2003** [comment]
The bash script works for me so I am quite happy.I'll maintain it as an out of tree patch if you don't want to accept it upstream.Regards,IainOn 22 Dec 2019 19:27, Christian Herzog <notifications@github.com> wrote:are you still interested in this?

**Comment by daduke** [comment]
too specific, Iain uses OOT patch

**Pull request closed without merging**
